"""create sources table

Revision ID: 2824dca34c34
Revises: 39c9c84f0d71
Create Date: 2026-09-17 13:19:04.381783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2824dca34c34'
down_revision = '39c9c84f0d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_sources_organization'), ['organization'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_source_type'), ['source_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_source_type'))
        batch_op.drop_index(batch_op.f('ix_sources_organization'))
        batch_op.drop_index(batch_op.f('ix_sources_name'))
        batch_op.drop_index(batch_op.f('ix_sources_is_active'))

    op.drop_table('sources')
    # ### end Alembic commands ###
