"""create markets table

Revision ID: 39c9c84f0d71
Revises: c735947bd0d2
Create Date: 2026-09-17 13:08:41.686127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c9c84f0d71'
down_revision = 'c735947bd0d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('nepali_name', sa.String(length=150), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('municipality', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('market_type', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_markets_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_markets_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_markets_market_type'), ['market_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_markets_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_markets_province'), ['province'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_markets_province'))
        batch_op.drop_index(batch_op.f('ix_markets_name'))
        batch_op.drop_index(batch_op.f('ix_markets_market_type'))
        batch_op.drop_index(batch_op.f('ix_markets_is_active'))
        batch_op.drop_index(batch_op.f('ix_markets_district'))

    op.drop_table('markets')
    # ### end Alembic commands ###
