"""add unique constraint to prices

Revision ID: 78be99bceddf
Revises: 20b05acced37
Create Date: 2026-09-17 14:59:03.519824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78be99bceddf'
down_revision = '20b05acced37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_prices_product_market_source_date', ['product_id', 'market_id', 'source_id', 'price_date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_constraint('uq_prices_product_market_source_date', type_='unique')

    # ### end Alembic commands ###
