"""create prices table

Revision ID: e37ad10b197d
Revises: 2824dca34c34
Create Date: 2026-09-17 13:24:25.838861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37ad10b197d'
down_revision = '2824dca34c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('average_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('source_reference', sa.String(length=500), nullable=True),
    sa.Column('freshness', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prices_collected_at'), ['collected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prices_freshness'), ['freshness'], unique=False)
        batch_op.create_index(batch_op.f('ix_prices_market_id'), ['market_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prices_price_date'), ['price_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_prices_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prices_source_id'), ['source_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prices_source_id'))
        batch_op.drop_index(batch_op.f('ix_prices_product_id'))
        batch_op.drop_index(batch_op.f('ix_prices_price_date'))
        batch_op.drop_index(batch_op.f('ix_prices_market_id'))
        batch_op.drop_index(batch_op.f('ix_prices_freshness'))
        batch_op.drop_index(batch_op.f('ix_prices_collected_at'))

    op.drop_table('prices')
    # ### end Alembic commands ###
